// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJKxK2MpUGWGRTNeHuJJ3vMhTNnvXbW0',
    appId: '1:53670484196:web:841d622c38a226e69634f1',
    messagingSenderId: '53670484196',
    projectId: 'mediquick-pbl',
    authDomain: 'mediquick-pbl.firebaseapp.com',
    storageBucket: 'mediquick-pbl.firebasestorage.app',
    measurementId: 'G-ETTKTWLMRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYNduE0k-9ZGB2rF9Ia7wqQxBquhqn5E',
    appId: '1:53670484196:android:237c899f7d28e7e69634f1',
    messagingSenderId: '53670484196',
    projectId: 'mediquick-pbl',
    storageBucket: 'mediquick-pbl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnakA548C_E29FuTzheKyU-4SF9Bks4JU',
    appId: '1:53670484196:ios:bf231bf919c4aa349634f1',
    messagingSenderId: '53670484196',
    projectId: 'mediquick-pbl',
    storageBucket: 'mediquick-pbl.firebasestorage.app',
    iosBundleId: 'com.example.mediquickPbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnakA548C_E29FuTzheKyU-4SF9Bks4JU',
    appId: '1:53670484196:ios:bf231bf919c4aa349634f1',
    messagingSenderId: '53670484196',
    projectId: 'mediquick-pbl',
    storageBucket: 'mediquick-pbl.firebasestorage.app',
    iosBundleId: 'com.example.mediquickPbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJKxK2MpUGWGRTNeHuJJ3vMhTNnvXbW0',
    appId: '1:53670484196:web:50ae68b94e69b4889634f1',
    messagingSenderId: '53670484196',
    projectId: 'mediquick-pbl',
    authDomain: 'mediquick-pbl.firebaseapp.com',
    storageBucket: 'mediquick-pbl.firebasestorage.app',
    measurementId: 'G-4KGBZ5T1K8',
  );
}
